{
 "title": "Evidently Numerical Target Drift Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataset_name", "label": "Dataset Name", "query": { "query": "label_values(dataset_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Rows Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:count{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Drift Score (p-value)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:drift{dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Features Correlations with Target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:current_correlations{kind=\"target\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Features Correlation with Prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "evidently:num_target_drift:current_correlations{kind=\"prediction\", dataset_name=\"${dataset_name:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}